version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/base-campaign-service/
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root
